### ISSUE TITLE
Предупреждения при компиляции

### ISSUE THREAD

**Issue by wzooroo** [krepostnoy/brain-of-infrared-rework-station#1]
`C:\ИК станция\kluch_5.2d\kluch_5.2d.ino:41:21: warning: extra tokens at end of #ifdef directive
C:\ИК станция\kluch_5.2d\kluch_5.2d.ino:44:21: warning: extra tokens at end of #ifdef directive
In file included from C:\ИК станция\kluch_5.2d\kluch_5.2d.ino:14:0:
C:\Users\home\Documents\Arduino\libraries\ClickBtnLong/ClickBtnLong.h:11:7: warning: extra qualification 'ClickBtnLong::' on member 'VerifiClick' [-fpermissive]
  bool ClickBtnLong::VerifiClick ();
       ^~~~~~~~~~~~

In file included from C:\Users\home\Documents\Arduino\libraries\ClickBtnLong\ClickBtnLong.cpp:4:0:
C:\Users\home\Documents\Arduino\libraries\ClickBtnLong\ClickBtnLong.h:11:7: warning: extra qualification 'ClickBtnLong::' on member 'VerifiClick' [-fpermissive]
  bool ClickBtnLong::VerifiClick ();
       ^~~~~~~~~~~~
`
Компилится но предупреждает.
Это не влияет на работу?

**Comment by krepostnoy** [comment]
IDE 1.8.19 "Скетч использует 17960 байт (55%) памяти устройства. Всего доступно 32256 байт.
Глобальные переменные используют 777 байт (37%) динамической памяти, оставляя 1271 байт для локальных переменных. Максимум: 2048 байт."
IDE 1.8.13 "Скетч использует 17960 байт (55%) памяти устройства. Всего доступно 32256 байт.
Глобальные переменные используют 777 байт (37%) динамической памяти, оставляя 1271 байт для локальных переменных. Максимум: 2048 байт."
В папке libraries только библиотеки из архива. Никаких предупреждений IDE не сделала. Расширенный вывод при компиляции тоже показал отсутствие предупреждений и ошибок.
