### ISSUE TITLE
Ошибка в схеме?

### ISSUE THREAD

**Issue by wzooroo** [krepostnoy/brain-of-infrared-rework-station#2]
**По скетчу** 

#define thermoCStop 6                             //CS MAX6675 "ВЕРХНЕГО" канала
#define thermoCSbott 7                            //CS MAX6675 "НИЖНЕГО" канала
#define thermoSO 8                                //DO=(SO) преобразователей термопар MAX6675
#define thermoCLK  9                              //SCK=(CLK) преобразователей термопар MAX6675

**по схеме**

#define thermoCStop 8                             //CS MAX6675 "ВЕРХНЕГО" канала
#define thermoCSbott 9                            //CS MAX6675 "НИЖНЕГО" канала
#define thermoSO 6                                //DO=(SO) преобразователей термопар MAX6675
#define thermoCLK  7                              //SCK=(CLK) преобразователей термопар MAX6675

или я ошибаюсь?

**Comment by krepostnoy** [comment]
Благодарю за обратную связь. Исправил схему.
