### ISSUE TITLE
Нет соединения(

### ISSUE THREAD

**Issue by wzooroo** [krepostnoy/brain-of-infrared-rework-station#3]
Подскажите, как подключить к irsp?
Хоть тресни прога не видит станцию(  Хотя в serial_port_plotter (не во всех версиях) графики рисует!
Я что-то делаю не так?

**Comment by wzooroo** [comment]
Разобрался!
Если SPP в скетче не за комментировать то будет ошибка.

**Comment by krepostnoy** [comment]
> Разобрался! Если SPP в скетче не за комментировать то будет ошибка.

Верно. Перед компиляцией, во вкладке Setting.h строку №2 нужно закомментировать, если желаете использовать ПО irsp.exe, а не SerialOortPlotter.
